# Importação do arquivo .csv

In [1]:
import pandas as pd

def converte_int(dado: str):
  try:
    return int(dado)
  except ValueError:
    return None

df = pd.read_csv("../../db/salas-de-exibicao.csv", sep=";")

# Renomeia colunas para padrão snake_case
df.columns = df.columns.str.lower()

In [2]:
df.head()

,nome_sala,registro_sala,cnpj_sala,situacao_sala,data_situacao_sala,data_inicio_funcionamento_sala,assentos_sala,assentos_cadeirantes,assentos_mobilidade_reduzida,assentos_obesidade,...,municipio_complexo,cep_complexo,uf_complexo,complexo_itinerante,operacao_usual,nome_exibidor,registro_exibidor,cnpj_exibidor,situacao_exibidor,nome_grupo_exibidor
0,CINE COMPANY JAGUARIUNA,5003332.0,10.615.866/0001-60,FECHADO,29/08/2011,16/12/2008,162.0,NaN,NaN,NaN,...,JAGUARIÚNA,13820-000,SP,NÃO,COMERCIAL,02 P D & ARAUJO EMPRESA CINEMATOGRAFICA LTDA,19954,10.615.866/0001-60,IRREGULAR,NÃO PERTENCE A NENHUM GRUPO EXIBIDOR
1,CINE COMPANY JAGUARIUNA SALA 01,5003331.0,10.615.866/0001-60,FECHADO,29/08/2011,16/12/2008,162.0,NaN,NaN,NaN,...,JAGUARIÚNA,13820-000,SP,NÃO,COMERCIAL,02 P D & ARAUJO EMPRESA CINEMATOGRAFICA LTDA,19954,10.615.866/0001-60,IRREGULAR,NÃO PERTENCE A NENHUM GRUPO EXIBIDOR
2,PARK SHOPPING 01,5003401.0,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,402.0,8.0,5.0,5.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK
3,PARK SHOPPING 02,5003402.0,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,370.0,8.0,4.0,4.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK
4,PARK SHOPPING 03,5003403.0,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,245.0,5.0,3.0,3.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK

In [3]:
# Removendo registros onde registro_sala é nulo
df = df.dropna(subset=['registro_sala'])

# Converter registro_sala para inteiro
df['registro_sala'] = df['registro_sala'].astype(int)

In [4]:
# Convertendo `assentos_sala` para inteiro
df['assentos_sala'] = df['assentos_sala'].astype(int)

In [5]:
df.head()

,nome_sala,registro_sala,cnpj_sala,situacao_sala,data_situacao_sala,data_inicio_funcionamento_sala,assentos_sala,assentos_cadeirantes,assentos_mobilidade_reduzida,assentos_obesidade,...,municipio_complexo,cep_complexo,uf_complexo,complexo_itinerante,operacao_usual,nome_exibidor,registro_exibidor,cnpj_exibidor,situacao_exibidor,nome_grupo_exibidor
0,CINE COMPANY JAGUARIUNA,5003332,10.615.866/0001-60,FECHADO,29/08/2011,16/12/2008,162,NaN,NaN,NaN,...,JAGUARIÚNA,13820-000,SP,NÃO,COMERCIAL,02 P D & ARAUJO EMPRESA CINEMATOGRAFICA LTDA,19954,10.615.866/0001-60,IRREGULAR,NÃO PERTENCE A NENHUM GRUPO EXIBIDOR
1,CINE COMPANY JAGUARIUNA SALA 01,5003331,10.615.866/0001-60,FECHADO,29/08/2011,16/12/2008,162,NaN,NaN,NaN,...,JAGUARIÚNA,13820-000,SP,NÃO,COMERCIAL,02 P D & ARAUJO EMPRESA CINEMATOGRAFICA LTDA,19954,10.615.866/0001-60,IRREGULAR,NÃO PERTENCE A NENHUM GRUPO EXIBIDOR
2,PARK SHOPPING 01,5003401,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,402,8.0,5.0,5.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK
3,PARK SHOPPING 02,5003402,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,370,8.0,4.0,4.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK
4,PARK SHOPPING 03,5003403,00.779.721/0054-53,EM FUNCIONAMENTO,24/04/2021,18/11/2011,245,5.0,3.0,3.0,...,SÃO CAETANO DO SUL,09531-190,SP,NÃO,COMERCIAL,CINEMARK BRASIL S.A,1843,00.779.721/0001-41,REGULAR,CINEMARK

In [6]:
# Exportando DataFrame para .csv tratado
df.to_csv("../../db/clean/salas-de-exibicao.csv", index=False)